# Generated by Django 3.2.10 on 2022-05-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20220531_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.location'),
        ),
    ]
